### ISSUE TITLE
Failed to activate the build-fpc package

### ISSUE THREAD

**Issue by santimonti** [idleberg/atom-build-fpc#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Linux Lite
**Thrown From**: [build-fpc](https://github.com/idleberg/atom-build-fpc) package 0.1.1

### Stack Trace

Failed to activate the build-fpc package

```
At /home/santiago/.atom/packages/build-fpc/lib/provider.js: Unexpected token (12:12)

SyntaxError: /home/santiago/.atom/packages/build-fpc/lib/provider.js: Unexpected token (12:12)
export const config = {
  customFreePascalArguments: {
    title: {-Co -Cr -Miso -gl},
    description: {-Co -Cr -Miso -gl},
    type: 'string',
    default: '{FILE_ACTIVE}',
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseIdent (/app.asar/node_modules/babylon/lib/parser/expression.js:818:10)
    at Parser.pp.parsePropertyName (/app.asar/node_modules/babylon/lib/parser/expression.js:694:135)
    at Parser.pp.parseObj (/app.asar/node_modules/babylon/lib/parser/expression.js:638:12)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseObjPropValue (/app.asar/node_modules/babylon/lib/parser/expression.js:652:99)
    at Parser.parseObjPropValue (/app.asar/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/app.asar/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseObjPropValue (/app.asar/node_modules/babylon/lib/parser/expression.js:652:99)
    at Parser.parseObjPropValue (/app.asar/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/app.asar/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-cursor-indent 0.3.3 
build 0.70.0 
build-fpc 0.1.1 
busy-signal 2.0.1 
intentions 1.1.5 
language-pascal 1.0.0 
linter 2.3.1 
linter-ui-default 1.8.1 
node_modules undefined 
pascal 1.2.1 
```

**Comment by idleberg** [comment]
How did you install the package? Does this happen right after installation? After a restart? When you load a project?

I'm suspicious about the following part since there's no mentioning of it anywhere in the code:

```
customFreePascalArguments: {
    title: {-Co -Cr -Miso -gl},
    description: {-Co -Cr -Miso -gl},
```

Unfortunately, I cannot reproduce this using macOS, Fedora or Windows 10
